version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  media_data:
  static_data: